{% set name = "boost-histogram" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/boost_histogram/boost_histogram-{{ version }}.tar.gz
  sha256: 88f2a58a77d273e9e09783036f23bb39ba2fcfc7e13d14639151245eb90ec0b2

build:
  number: 0
  script:
    - export CMAKE_BUILD_PARALLEL_LEVEL=1  # [linux and ppc64le]
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}  # [not (linux and ppc64le)]
    # Workaround for stalled jobs on travis
    - bash -c 'while true; do echo "Prevent stall"; sleep 60; done' &  # [linux and ppc64le]
    - {{ PYTHON }} -m pip install . -vvv
    - kill %1  # [linux and ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip >=18
    - setuptools_scm
  run:
    - python
    - numpy
    - dataclasses  # [py<37]

test:
  source_files:
    - tests
  imports:
    - boost_histogram
  requires:
    - pytest
    - pytest-benchmark
  commands:
    - pytest .

about:
  home: https://github.com/scikit-hep/boost-histogram
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    The official Boost.Histogram Python bindings. Provides fast, efficient
    histogramming with a variety of different storages combined with dozens of
    composable axes. Part of the [Scikit-HEP](https://scikit-hep.org) family.
  dev_url: https://github.com/scikit-hep/boost-histogram
  doc_url: https://boost-histogram.readthedocs.io

extra:
  recipe-maintainers:
    - chrisburr
    - henryiii
    - HDembinski
