{% set name = "boost-histogram" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/boost_histogram/boost-histogram-{{ version }}.tar.gz
  sha256: a79b472aa28579f3936a8264951bfafec3abf43f6cedc7476081b8ff0dc757a8

build:
  number: 3
  script: NPY_NUM_BUILD_JOBS=1 {{ PYTHON }} -m pip install . -vvv  # [linux and ppc64le]
  script: {{ PYTHON }} -m pip install . -vvv  # [not (linux and ppc64le)]
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('cxx') }}           # [not win]
    - vs2017_{{ target_platform }}    # [win]
  host:
    - python
    - pip >=18
    - numpy
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  imports:
    - boost_histogram
  requires:
    - pytest
    - pytest-benchmark
  commands:
    - pytest .

about:
  home: https://github.com/scikit-hep/boost-histogram
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Boost::Histogram Python wrapper.
  dev_url: https://github.com/scikit-hep/boost-histogram
  doc_url: https://boost-histogram.readthedocs.io

extra:
  recipe-maintainers:
    - chrisburr
    - henryiii
    - HDembinski
