{% set name = "boost-histogram" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/boost_histogram/boost_histogram-{{ version }}.tar.gz
  sha256: 97146f735f467d506976a047f3f237ce59840a952fd231f5f431f897fb006cdd

build:
  number: 0
  skip: true  # [linux and ppc64le and python_impl == 'pypy']
  script:
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}  # [not (linux and ppc64le)]
    - {{ PYTHON }} -m pip install . -v

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip >=18
    - setuptools_scm
  run:
    - python
    - numpy
    - typing_extensions  # [py<38]

test:
  source_files:
    - tests
  imports:
    - boost_histogram
  requires:
    - pytest >=6
    - pytest-benchmark
  commands:
    - pytest --benchmark-disable

about:
  home: https://github.com/scikit-hep/boost-histogram
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    The official Boost.Histogram Python bindings. Provides fast, efficient
    histogramming with a variety of different storages combined with dozens of
    composable axes. Part of the [Scikit-HEP](https://scikit-hep.org) family.
  dev_url: https://github.com/scikit-hep/boost-histogram
  doc_url: https://boost-histogram.readthedocs.io

extra:
  recipe-maintainers:
    - chrisburr
    - henryiii
    - HDembinski
