{% set name = "boost-histogram" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/boost_histogram/boost_histogram-{{ version }}.tar.gz
  sha256: eb2205e7cac21c3742b19ea147359c588e07a4f3b719d58c6ad6009fee423fce

build:
  number: 0
  script: NPY_NUM_BUILD_JOBS=1 {{ PYTHON }} -m pip install . -vvv  # [linux and ppc64le]
  script: {{ PYTHON }} -m pip install . -vvv  # [not (linux and ppc64le)]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip >=18
    - setuptools_scm
  run:
    - python
    - numpy
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  imports:
    - boost_histogram
  requires:
    - pytest
    - pytest-benchmark
  commands:
    - pytest .

about:
  home: https://github.com/scikit-hep/boost-histogram
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Boost::Histogram Python wrapper.
  dev_url: https://github.com/scikit-hep/boost-histogram
  doc_url: https://boost-histogram.readthedocs.io

extra:
  recipe-maintainers:
    - chrisburr
    - henryiii
    - HDembinski
