provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: oA/sicKzbE0pqXsCZ7j0OUlUFDQDRlPQmtT7sx7kaxdAkxioTWUn5nI/5elj0rS59xMumzfS9THDc7gQKA9N7n8deLvZuWtb2Fh5y69bI9vbcf7pXRA8548O9s8gk1JcI0SC7/s045wLnOx86Uqh0bCeMTft0gvQ3eAR1RAbp/FCFuJ5PHV5cRh1qZpZuxeqe007XU1ZCd3z7MB/vd3Ok4wYlmwdUBSKtUsyKOEy3y4zif/QSjF+6oIm9ZX2JDbMvl+XZpnjd4pxD1y0VHVPumnBFqvaeuplmoCF0CJSI0NKu8Tdu6GMXx9xsK4I/uX5NcMNw6VVENQm8dQvPXA1MuDFffD5aFL0A/WgNtoHnkuOQcP6E72DT49SPGfWKdaM8EgXdE2yAqN6tddrn7Ab7GqVUuDUCb2rL5W4kbG3QJaQ46Mv3xvZCL5jnjNSqJXJsP76FfcMEg6l0S0vmYl+pJrop91Z0f8w/tIcRmLT0nS9yiF0xTxHJgYp0R1KGrpPnfOu8El9sd+Jg2pyJjd/HQbbbhGrfnSkbb6RXTlegDiFZX5mfK8XBwvciHOb+c2yM6HovvJRwbqFwwFqyWaMMZGxyBbcD2DYEe/K5yz7ajIfoY1hGgWsqZR/xT3eMthoVd6VfXLkMmfDbwEVRuCL2O4avxkgWj07Ba8e650fv8o=}
conda_forge_output_validation: true
bot:
  automerge: true
