# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

[project]
name = "boost-histogram-feedstock"
version = "3.47.0"
description = "Pixi configuration for conda-forge/boost-histogram-feedstock"
authors = ["@conda-forge/boost-histogram"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "linux-ppc64le", "osx-64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
inspect-all = "inspect_artifacts --all-packages"
build = "rattler-build build --recipe recipe"
"build-win_64_python3.12.____cpython" = "rattler-build build --recipe recipe -m .ci_support/win_64_python3.12.____cpython.yaml"
"inspect-win_64_python3.12.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_python3.12.____cpython.yaml"

[feature.smithy.dependencies]
conda-smithy = "*"

[feature.smithy.tasks]
build-locally = "python ./build-locally.py"
smithy = "conda-smithy"
rerender = "conda-smithy rerender"
lint = "conda-smithy lint recipe"

[environments]
smithy = ["smithy"]
